version: "3.9"
services:
  web:
    build: 
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    ports:
      - 8080:8080
    tty: true
    stdin_open: true
    privileged: true